Repository CodersCamp2021-HK/CodersCamp2021.Project.Fullstack, pull requests merged in 2022-04, with the labels that each got.

#137 add logo
  packages/client/src/App.css
  packages/client/src/logo.svg
Labels: ⏱ 1 minute PR, 🦄 UX/UI design

#136 add basic color theme
  packages/client/src/App.tsx
Labels: ⏱ 1 minute PR

#139 Users tests don't send mails
  packages/server/src/auth/domain/RegisterAsUserHandler.ts
  packages/server/src/orders/domain/CreateOrderHandler.ts
  packages/server/test/shared/E2eFixture.ts
Labels: 🐛 fix, ⏱ 1 minute PR
